language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

env:
    - SYMFONY_VERSION="~2.7.0"

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION="~2.3.0"
        - php: 5.6
          env: SYMFONY_VERSION="~2.7.0"
        - php: 5.6
          env: SYMFONY_VERSION="~2.8.0@dev"
        - php: 5.6
          env: SYMFONY_VERSION="~3.0.0@dev"

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
    - composer config -q -g github-oauth.github.com ${GITHUB_OAUTH_TOKEN}

install: composer update --prefer-dist --ignore-platform-reqs

script: vendor/bin/phpunit
